name: PyGeoHack
channels:
  - conda-forge
  - defaults
dependencies:
  # NetCDF files
  - xarray
  - netcdf4
  - nc-time-axis
  # CMIP6
  - intake-esm
  - gcsfs
  - zarr
  # Regrid
  - esmpy
  - xesmf
  # Plots
  - proplot
  - matplotlib=3.2
  - cartopy
  - python-graphviz
